CREATE TABLE IF NOT EXISTS booking_seats (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userId INT UNSIGNED NOT NULL,
    movieId INT UNSIGNED NOT NULL,
    seatId INT UNSIGNED NOT NULL,
    
